apiVersion: v1
kind: ConfigMap
metadata:
  name: sai-cms-configmap
  namespace: sai-prod
data:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "1337"

  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: "db-postgres-cluster-001-do-user-18951983-0.f.db.ondigitalocean.com"
  DATABASE_PORT: "25060"
  DATABASE_NAME: "sai_db"
  DATABASE_SSL: "true"
