apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai-cms
  namespace: sai-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sai-cms
  template:
    metadata:
      labels:
        app: sai-cms
    spec:
      # Fix volume permissions for the "node" user (uid 1000)
      initContainers:
        - name: fix-uploads-perms
          image: busybox:1.36
          command: ["sh", "-lc", "mkdir -p /data && chown -R 1000:1000 /data"]
          volumeMounts:
            - name: uploads
              mountPath: /data

      containers:
        - name: sai-cms
          image: khedhrije/sai-admin:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 1337

          envFrom:
            - configMapRef:
                name: sai-cms-configmap
            - secretRef:
                name: sai-cms-secrets

          volumeMounts:
            - name: uploads
              mountPath: /opt/app/public/uploads

          readinessProbe:
            tcpSocket:
              port: 1337
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 1337
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: sai-cms-uploads-pvc
