apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sai-cms-ingress
  namespace: sai-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cms.sai-technologie.com
      secretName: sai-technologie-tls
  rules:
    - host: cms.sai-technologie.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sai-cms-service
                port:
                  number: 80
