apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai-portal
  namespace: sai-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sai-portal
  template:
    metadata:
      labels:
        app: sai-portal
    spec:
      containers:
        - name: sai-portal
          image: khedhrije/sai-portal:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5173

          envFrom:
            - configMapRef:
                name: sai-portal-configmap

          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

      imagePullSecrets:
        - name: imageregistry
