apiVersion: v1
kind: ConfigMap
metadata:
  name: sai-admin-configmap
  namespace: sai-prod
data:
  # These are PUBLIC (exposed in /env-config.js). Do not put secrets here.
  VITE_APP_NAME: "SAI TECHNOLOGIE"
  VITE_APP_VERSION: "1.0.0"
  VITE_APP_BASE_URL: "https://sai-technologie.com"
  VITE_APP_STRAPI_BASE_URL: "https://cms.sai-technologie.com"
  VITE_APP_STRAPI_API_URL: "https://cms.sai-technologie.com/api"
  VITE_APP_STRAPI_GRAPHQL_URL: "https://cms.sai-technologie.com/graphql"
