apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sai-admin-ingress
  namespace: sai-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.sai-technologie.com
      secretName: admin-sai-technologie-tls
  rules:
    - host: admin.sai-technologie.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sai-admin-service
                port:
                  number: 80
